# Generated by Django 5.0.6 on 2025-01-15 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0087_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='myapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='myapp.product'),
            preserve_default=False,
        ),
    ]
