# Generated by Django 5.0.6 on 2025-01-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_feedback_product_rating_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdCat',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=255)),
            ],
        ),
    ]
