# Generated by Django 5.0.6 on 2025-02-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
