# Generated by Django 5.0.6 on 2025-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
