# Generated by Django 5.0.6 on 2025-02-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_seasonalcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seasonalcategory')),
            ],
        ),
    ]
