# Generated by Django 5.0.6 on 2025-02-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0094_seasonalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonalproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seasonal_products/'),
        ),
    ]
