# Generated by Django 5.0.6 on 2025-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_seasonalproduct_description_seasonalproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('description', models.TextField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('event_date', models.DateField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
            ],
        ),
    ]
